In [4]:
	
import copy
from IPython.display import display, Video
from io import BytesIO
import os

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.ticker import MultipleLocator, FormatStrFormatter
import imageio.v2 as imageio

import tempfile

from kmeans import Kmeans, assign_data_to_centroids, kmeans_loss_function
from kmeans_plotting import Plot1DKmeans, Plot2DKmeans

%matplotlib inline

ModuleNotFoundError: No module named 'imageio'

In [5]:
import pandas as pd

In [1]:
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

In [10]:
	
iris = load_iris() #cargando el dataframe iris es un diccionario con muchas cosas
iris_df = pd.DataFrame(data= iris.data, columns= iris.feature_names)

iris_df['original_label'] = iris.target #en la clusterizacion no lo vamos a hacer con la etiqueta original
iris_df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),original_label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [25]:
#sabemos que hay 3 clases, vamos a ir cambiando el random_state
kmeans = KMeans(n_clusters=3, max_iter=300, random_state=2) #kmeans le doy parametros 
#tengo que darle el n_clusters que es k
#mas_iter es el numero de iteraciones 
kmeans.fit(iris.data)
print(kmeans.labels_)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]

In [37]:
kmeans = KMeans(n_clusters=3, max_iter=300, random_state=4)
kmeans.fit(iris.data)
print(kmeans.labels_)
#AQUI compruebo que sin el random cambia y asigna diferentes la entradas y los ejemplos, CAMBIA LA ASIGNACION

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 0 0 0 2 0 0 0 0
 0 0 2 2 0 0 0 0 2 0 2 0 2 0 0 2 2 0 0 0 0 0 2 0 0 0 0 2 0 0 0 2 0 0 0 2 0
 0 2]

In [38]:
from sklearn import preprocessing

cols = iris_df.columns[:-2]  # Exclude 'target' and 'cluster' columns

iris_df_norm = iris_df[cols].copy()
iris_df_norm[cols] = preprocessing.normalize(iris_df[cols])
iris_df_norm["original_label"] = iris_df["original_label"]
iris_df_norm.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  original_label
count         150.000000        150.000000         150.000000      150.000000
mean            0.761040          0.409694           0.462357        1.000000
std             0.037861          0.102980           0.165590        0.819232
min             0.677067          0.243876           0.167902        0.000000
25%             0.728116          0.335264           0.251236        0.000000
50%             0.765579          0.359808           0.544311        1.000000
75%             0.792181          0.527902           0.594814        2.000000
max             0.862360          0.607471           0.647210        2.000000

In [43]:
	#Vemos que las flores del tipo 0 me las está metiendo todas en un cluster, lo está haciendo muy bien. Pero los otros dos, me los está dividiendo en dos, entonces no lo está ajustando pien. Esto puede ser
#por el escalado, así que vamos a probar con el reescalado.
kmeans_norm = KMeans(n_clusters=3, max_iter=300, random_state=3)
kmeans_norm.fit(iris_df_norm[cols])

iris_df_norm["cluster"] = kmeans_norm.labels_
iris_df_norm.groupby(['original_label','cluster']).agg({'sepal length (cm)': 'count'})

                        sepal length (cm)
original_label cluster
0              1                       50
1              0                       42
               2                        8
2              0                        1
               2                       49

In [ ]:
kmeans_norm = KMeans(n_clusters=3, max_iter=300, random_state=2)
kmeans_norm.fit(iris_df_norm[cols])
#n_clusters=3 por eso cuando me saca la tabla en los clusters el primer cluster es 0, el segundo 1 el tercero 2 
#random_state es para iniciar en el mismo punto FIJO LA ALEATORIEDAD, 

iris_df_norm["cluster"] = kmeans_norm.labels_
iris_df_norm.groupby(['original_label','cluster']).agg({'sepal length (cm)': 'count'})

                        sepal length (cm)
original_label cluster
0              1                       50
1              0                       42
               2                        8
2              0                        1
               2                       49